apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/bosh-wang/flask-api-image
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
            ephemeral-storage: "2Gi"
          limits:
            cpu: 200m
            memory: 1Gi
            ephemeral-storage: "3Gi"
        env:
          - name: DB_HOST
            value: "citus-coordinator-service"
          - name: DB_NAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "backend"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "backend"
          - name: SENDER_EMAIL
            value: "wangbosh66@gmail.com"
          - name: SENDER_PASSWORD
            value: "nuys wgiz vyib wqbh"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
