apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
