apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: citus-coordinator
---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: citus-worker

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379


