name: black-action
on:
  push:
    branches:
      - sys/deploy-k8s-db
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: "Format Python code with psf/black"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some Python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: ./temp/app
        run: docker build -t ghcr.io/estheryang2000/meal_provider_2024-temp:${{ github.sha }} .

      - name: Push Docker image
        working-directory: ./temp/app
        run: docker push ghcr.io/estheryang2000/meal_provider_2024-temp:${{ github.sha }}

      - name: Set up Kubernetes config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Deploy
        run: |
          kubectl apply -f kubernetes/test/deploy-test.yaml --validate=false
